### ISSUE TITLE
Kamera stellt nicht schafr

### ISSUE THREAD

**Issue by FHenke** [froid1911/greencity#5]
Die Kamera von meinem Handy stellt nicht scharf, es ist ahezu unmöglich ein Foto so zu machen, dass man etwas lesen kann (Samsung Galaxy S4 active )

**Comment by froid1911** [comment]
CameraPreview mit Camera ersetzen +
-  modal mit Textarea, Vorschaubild und buttons 
- buttons: redo, publish
